/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package listadeexercicios;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Oi!";
    }

    public static void main(String[] args) {
        System.out.println("Lista de Execicios:");
        System.out.println("Escolha uma Questão de 1 a 35:");
        
        Scanner leitor = new Scanner(System.in);
        int x = leitor.nextInt();
        
        switch (x) {
            case 1:
                System.out.println("Caso 1.");
                break;
                        
            default:
                System.out.println(":(");
                break;
        }

    }
}
